"""initial environments table

Revision ID: 0001
Revises:
Create Date: 2026-08-01

Baseline matching db/models.py as of the Phase 1 schema. Written by hand rather
than autogenerated: there was no live database to diff against at the time.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# create_table emits CREATE TYPE for this implicitly, so it must NOT also be
# created explicitly — that produces a duplicate CREATE TYPE and fails on
# PostgreSQL. It is named here only so downgrade() can drop it; dropping the
# table alone leaves the type behind and breaks the next upgrade.
environment_status = sa.Enum(
    "PENDING",
    "PROVISIONING",
    "RUNNING",
    "STOPPING",
    "STOPPED",
    "FAILED",
    name="environmentstatus",
)


def upgrade() -> None:
    op.create_table(
        "environments",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("owner", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            environment_status,
            nullable=False,
        ),
        sa.Column("template", sa.String(length=50), nullable=False),
        sa.Column("container_ids", sa.JSON(), nullable=False),
        sa.Column("network_id", sa.String(length=100), nullable=True),
        sa.Column("host_port", sa.Integer(), nullable=True),
        sa.Column("ttl_seconds", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stopped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("celery_task_id", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    op.drop_table("environments")
    environment_status.drop(op.get_bind(), checkfirst=True)
